# Generated by Django 5.2.14 on 2026-05-21 00:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pagado', models.BooleanField(default=False)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='tickets/qrs/')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
