# Generated by Django 5.2.14 on 2026-05-21 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='asistente',
            field=models.ForeignKey(limit_choices_to={'rol': 'ASISTENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_compradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrada',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='events.preciocategoria'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='events.evento'),
        ),
    ]
